[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
thiserror = "1.0"
network = { path = "../network" }
bincode = "1.3.3"
serde = "1"
serde_derive = "1"
